#     ____    _                _   _   ___ 
#    / ___|  (_)  ____   ___  | | | | |_ _|
#    \___ \  | | |_  /  / _ \ | | | |  | | 
#     ___) | | |  / /  |  __/ | |_| |  | | 
#    |____/  |_| /___|  \___|  \___/  |___|
#          by fernanACM                                    

#change your size easily with SizeUI, get small and 
#big with just one form.

#Permission: sizeui.acm

#Prefix SizeUI
Prefix: "§l§7[§eSizeUI§7]§8»§r "

#==================================================
#                  MESSAGES RESET
MessageReset: "§aIts size has returned to §dNormal."
#==================================================
#                Scale levels: Small
MessageSmall-1: "§aIts size has been changed to §dLEVEL 1."

MessageSmall-2: "§aIts size has been changed to §dLEVEL 2."

MessageSmall-3: "§aIts size has been changed to §dLEVEL 3."

MessageSmall-4: "§aIts size has been changed to §dLEVEL 4."

MessageSmall-5: "§aIts size has been changed to §dLEVEL 5."

MessageSmall-6: "§aIts size has been changed to §dLEVEL 6."

MessageSmall-7: "§aIts size has been changed to §dLEVEL 7."
#===================================================
#                Scale levels: Big
MessageBig-1: "§aIts size has been changed to §dLEVEL 1."

MessageBig-2: "§aIts size has been changed to §dLEVEL 2."

MessageBig-3: "§aIts size has been changed to §dLEVEL 3."

MessageBig-4: "§aIts size has been changed to §dLEVEL 4."
#
#
#===================================================
#                MESSAGES FORM
#===================================================
#                Buttons Menu: General
ResetButton: "§l§cReset\n§0§rNormal"
BigButton: "§l§3Big\n§r§0Increase size"
SmallButton: "§l§3Small\n§r§0Reduce size"
ExitButton: "§4§lClose menu"
#
#===================================================
#                Content Menu: Small
Content-Menu-Small: "§eSelect the level you want:"
#===================================================
#                Buttons messages: Small
SmallButtonLV-1: "§6§lLevel 1\n§r§0Scale 0.3"

SmallButtonLV-2: "§6§lLevel 2\n§r§0Scale 0.4"

SmallButtonLV-3: "§6§lLevel 3\n§r§0Scale 0.5"

SmallButtonLV-4: "§6§lLevel 4\n§r§0Scale 0.6"

SmallButtonLV-5: "§6§lLevel 5\n§r§0Scale 0.7"

SmallButtonLV-6: "§6§lLevel 6\n§r§0Scale 0.8"

SmallButtonLV-7: "§6§lLevel 7\n§r§0Scale 0.9"

ExitSmall: "§c§lRETURN\n§r§0Back to menu"
#
#===================================================
#                Content Menu: Big
Content-Menu-Big: "§eSelect the level you want:"
#===================================================
#                Buttons messages: Big
BigButtonLV-1: "§6§lLevel 1\n§r§0Scale 2.0"

BigButtonLV-2: "§6§lLevel 2\n§r§0Scale 3.0"

BigButtonLV-3: "§6§lLevel 3\n§r§0Scale 4.0"

BigButtonLV-4: "§6§lLevel 4\n§r§0Scale 5.0"

ExitBig: "§c§lRETURN\n§r§0Back to menu"
#
#===================================================